// <auto-generated />
using System;
using DddInPractice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DddInPractice.Data.Migrations
{
    [DbContext(typeof(DddInPracticeContext))]
    [Migration("20200316001353_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DddInPractice.Logic.SnackMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SnackMachines");
                });

            modelBuilder.Entity("DddInPractice.Logic.SnackMachine", b =>
                {
                    b.OwnsOne("DddInPractice.Logic.Money", "MoneyInside", b1 =>
                        {
                            b1.Property<Guid>("SnackMachineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FiveDollarCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("FiveDollarCount")
                                .HasColumnType("int")
                                .HasDefaultValue(0);

                            b1.Property<int>("OneCentCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("OneCentCount")
                                .HasColumnType("int")
                                .HasDefaultValue(0);

                            b1.Property<int>("OneDollarCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("OneDollarCount")
                                .HasColumnType("int")
                                .HasDefaultValue(0);

                            b1.Property<int>("QuarterCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("QuarterCount")
                                .HasColumnType("int")
                                .HasDefaultValue(0);

                            b1.Property<int>("TenCentCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("TenCentCount")
                                .HasColumnType("int")
                                .HasDefaultValue(0);

                            b1.Property<int>("TwentyDollarCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("TwentyDollarCount")
                                .HasColumnType("int")
                                .HasDefaultValue(0);

                            b1.HasKey("SnackMachineId");

                            b1.ToTable("SnackMachines");

                            b1.WithOwner()
                                .HasForeignKey("SnackMachineId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
